### ISSUE TITLE
Issues with QR Code not generating

### ISSUE THREAD

**Issue by mattmillen888** [LabD/wagtail-2fa#8]
Hi There, we have just install this locally on a dev project. (Love the Idea of this by the way) however for some reason when i click manage 2fa on a user(site.com/admin/2fa/devices/new)  the QR Code is not generating and shows as a broken link. can you think why this might be?

![screen shot 2018-05-29 at 10 26 26](https://user-images.githubusercontent.com/25214970/40632473-cee8ff76-632a-11e8-905a-4524c4cfb3d0.png)

**Comment by pimvernooij** [comment]
Hi,

The image is rendered from the url http://127.0.0.1:8000/cms/2fa/devices/qr-code - so it probably gives an error, including a stacktrace. Could you paste that?

Also, for a working example project, please see the sandox directory in the repository. You can run the sandbox by running `make sandbox` from the project root.

**Comment by mattmillen888** [comment]
Hey Pim, Thanks for the quick response. 

[29/May/2018 09:46:13] "GET /admin/2fa/devices/new HTTP/1.1" 200 12367
[29/May/2018 09:46:13] "GET /assets/wagtailadmin/css/core.css HTTP/1.1" 200 77729
[29/May/2018 09:46:13] "GET /admin/2fa/devices/qr-code HTTP/1.1" 200 0
Traceback (most recent call last):
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.5/socket.py", line 593, in write
    return self._sock.send(b)
  File "/usr/lib/python3.5/ssl.py", line 861, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.5/ssl.py", line 586, in write
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1844)
[29/May/2018 09:46:13] "GET /admin/2fa/devices/qr-code HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.5/socket.py", line 593, in write
    return self._sock.send(b)
  File "/usr/lib/python3.5/ssl.py", line 861, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.5/ssl.py", line 586, in write
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1844)

**Comment by mattmillen888** [comment]
Django==1.11
wagtail==2.1
wagtail-2fa==1.0.0
